# Generated by Django 5.2.12 on 2026-08-11 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcs', '0003_physicsconfig_dataset_physics_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample', models.CharField(db_index=True, help_text='PCS composed name of the validated sample', max_length=255)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('validated', 'Validated'), ('failed', 'Failed')], max_length=20)),
                ('benchmarks', models.JSONField(blank=True, default=list)),
                ('invalidated', models.JSONField(blank=True, default=list)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('details_url', models.CharField(blank=True, default='', max_length=500)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('received_from', models.CharField(blank=True, default='', max_length=100)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pcs_validation_result',
                'ordering': ['sample', 'revision', '-received_at'],
                'indexes': [models.Index(fields=['sample', 'revision', '-received_at'], name='pcs_valresult_latest')],
            },
        ),
    ]
