# Generated by Django 5.2.12 on 2026-08-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcs', '0004_validationresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pandatasks',
            name='task_name',
            field=models.CharField(db_index=True, max_length=300),
        ),
    ]
