# Generated by Django 5.2.12 on 2026-08-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcs', '0005_pandatasks_task_name_nonunique'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvgenMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=500, unique=True)),
                ('obsolete', models.BooleanField(default=False)),
                ('set_by', models.CharField(blank=True, default='', max_length=150)),
                ('set_at', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'pcs_evgen_mark',
                'ordering': ['path'],
            },
        ),
    ]
