# Generated by Django 5.2.12 on 2026-09-06 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcs', '0007_evgenmark_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveredOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pandaid', models.BigIntegerField(db_index=True)),
                ('did', models.CharField(max_length=500)),
                ('scope', models.CharField(default='epic', max_length=100)),
                ('kind', models.CharField(choices=[('FULL', 'FULL'), ('RECO', 'RECO')], max_length=8)),
                ('segment', models.CharField(blank=True, db_index=True, default='', max_length=200)),
                ('events', models.BigIntegerField(blank=True, null=True)),
                ('bytes', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('delivered', 'Delivered'), ('pending', 'Pending'), ('diverted', 'Diverted'), ('lost', 'Lost')], db_index=True, default='delivered', max_length=16)),
                ('reason', models.TextField(blank=True, default='')),
                ('registered_did', models.CharField(blank=True, default='', max_length=500)),
                ('reported_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('panda_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivered_outputs', to='pcs.pandatasks')),
                ('prod_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivered_outputs', to='pcs.prodtask')),
            ],
            options={
                'db_table': 'pcs_delivered_output',
                'ordering': ['prod_task', 'segment', 'kind'],
                'indexes': [models.Index(fields=['status', 'prod_task'], name='pcs_deliver_status_9fe76f_idx')],
                'constraints': [models.UniqueConstraint(fields=('prod_task', 'did'), name='pcs_delivered_output_unique_did')],
            },
        ),
    ]
