# Generated by Django 5.2.12 on 2026-09-12 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcs', '0008_deliveredoutput'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgroundtag',
            name='lifecycle',
            field=models.CharField(choices=[('active', 'Active'), ('retired', 'Retired'), ('invalid', 'Invalid'), ('superseded', 'Superseded')], default='active', max_length=16),
        ),
        migrations.AddField(
            model_name='backgroundtag',
            name='lifecycle_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backgroundtag',
            name='lifecycle_by',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='backgroundtag',
            name='lifecycle_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='backgroundtag',
            name='superseded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pcs.backgroundtag'),
        ),
        migrations.AddField(
            model_name='evgentag',
            name='lifecycle',
            field=models.CharField(choices=[('active', 'Active'), ('retired', 'Retired'), ('invalid', 'Invalid'), ('superseded', 'Superseded')], default='active', max_length=16),
        ),
        migrations.AddField(
            model_name='evgentag',
            name='lifecycle_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evgentag',
            name='lifecycle_by',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='evgentag',
            name='lifecycle_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='evgentag',
            name='superseded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pcs.evgentag'),
        ),
        migrations.AddField(
            model_name='physicsconfig',
            name='lifecycle',
            field=models.CharField(choices=[('active', 'Active'), ('retired', 'Retired'), ('invalid', 'Invalid'), ('superseded', 'Superseded')], default='active', max_length=16),
        ),
        migrations.AddField(
            model_name='physicsconfig',
            name='lifecycle_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='physicsconfig',
            name='lifecycle_by',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='physicsconfig',
            name='lifecycle_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='physicsconfig',
            name='superseded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pcs.physicsconfig'),
        ),
        migrations.AddField(
            model_name='physicstag',
            name='lifecycle',
            field=models.CharField(choices=[('active', 'Active'), ('retired', 'Retired'), ('invalid', 'Invalid'), ('superseded', 'Superseded')], default='active', max_length=16),
        ),
        migrations.AddField(
            model_name='physicstag',
            name='lifecycle_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='physicstag',
            name='lifecycle_by',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='physicstag',
            name='lifecycle_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='physicstag',
            name='superseded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pcs.physicstag'),
        ),
        migrations.AddField(
            model_name='recotag',
            name='lifecycle',
            field=models.CharField(choices=[('active', 'Active'), ('retired', 'Retired'), ('invalid', 'Invalid'), ('superseded', 'Superseded')], default='active', max_length=16),
        ),
        migrations.AddField(
            model_name='recotag',
            name='lifecycle_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recotag',
            name='lifecycle_by',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='recotag',
            name='lifecycle_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='recotag',
            name='superseded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pcs.recotag'),
        ),
        migrations.AddField(
            model_name='simutag',
            name='lifecycle',
            field=models.CharField(choices=[('active', 'Active'), ('retired', 'Retired'), ('invalid', 'Invalid'), ('superseded', 'Superseded')], default='active', max_length=16),
        ),
        migrations.AddField(
            model_name='simutag',
            name='lifecycle_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='simutag',
            name='lifecycle_by',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='simutag',
            name='lifecycle_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='simutag',
            name='superseded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pcs.simutag'),
        ),
        migrations.CreateModel(
            name='IdentityHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=64)),
                ('record_id', models.BigIntegerField()),
                ('operation', models.CharField(max_length=16)),
                ('before', models.JSONField(null=True)),
                ('after', models.JSONField(null=True)),
                ('changed_at', models.DateTimeField()),
                ('database_user', models.CharField(max_length=100)),
                ('actor', models.CharField(blank=True, max_length=100)),
                ('reason', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'pcs_identity_history',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['table_name', 'record_id', 'id'], name='pcs_identity_history_lookup')],
            },
        ),
    ]
